//! Layer 1: container parsing integration tests.
//!
//! These tests use the public `Archive::parse` API (via `crate::Archive`) to
//! validate that known-good `.7z` fixtures parse correctly end-to-end:
//! correct file count, names, coder types, and sizes.
//!
//! Fixtures live in `corpora/fixtures/archives/` and are committed to the repo.

use crate::container::{Archive as ContainerArchive, MethodId};
use crate::Archive;

fn fixture_bytes(name: &str) -> Vec<u8> {
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let path = manifest.join("corpora/fixtures/archives").join(name);
    std::fs::read(&path)
        .unwrap_or_else(|e| panic!("could not read fixture {}: {e}", path.display()))
}

// ── Live tests: Copy-coder fixtures ──────────────────────────────────────────

/// Parse `copy_only.7z` (generated by 7zz, committed as a known-good fixture).
///
/// Verifies: single file, correct name, Copy coder, correct payload size.
#[test]
fn parses_copy_only_archive() {
    let bytes = fixture_bytes("copy_only.7z");
    let archive = Archive::parse(&bytes).expect("copy_only.7z must parse without error");

    assert_eq!(archive.file_count(), 1, "expected 1 file");
    assert_eq!(
        archive.file_name(0),
        Some("8z-fixture-input.txt"),
        "file name mismatch"
    );

    // Drill into the container layer to verify the coder type.
    let container = ContainerArchive::parse(&bytes).expect("container parse failed");
    let ms = container
        .header
        .main_streams
        .as_ref()
        .expect("archive must have main_streams");
    assert_eq!(ms.folders.len(), 1);
    let folder = &ms.folders[0];
    assert_eq!(folder.coders.len(), 1);
    assert_eq!(
        folder.coders[0].method_id,
        MethodId::copy(),
        "expected Copy coder"
    );

    // Payload is the 19-byte literal "Hello, 7z umbrella!"
    assert_eq!(container.packed_data, b"Hello, 7z umbrella!");
}

/// Parse `copy_only_64k.7z` — a larger Copy archive used in oracle tests.
#[test]
fn parses_copy_only_64k_archive() {
    let bytes = fixture_bytes("copy_only_64k.7z");
    let archive = Archive::parse(&bytes).expect("copy_only_64k.7z must parse without error");

    assert_eq!(archive.file_count(), 1);
    assert_eq!(archive.file_name(0), Some("random_64k.bin"));

    let container = ContainerArchive::parse(&bytes).expect("container parse failed");
    let ms = container.header.main_streams.as_ref().unwrap();
    let folder = &ms.folders[0];
    assert_eq!(folder.coders[0].method_id, MethodId::copy());

    // 64 KiB of uncompressed data
    assert_eq!(container.packed_data.len(), 65_536);
}

// ── Ignored stubs: codecs not yet committed ───────────────────────────────────

/// Parse an LZMA-compressed `.7z` archive generated by `7zz`.
///
/// Requires `corpora/fixtures/archives/lzma_default.7z` to exist (committed
/// once the oracle fixture generator is run for the LZMA coder).
#[test]
fn parses_lzma_default_archive() {
    let bytes = fixture_bytes("lzma_default.7z");
    let archive = Archive::parse(&bytes).expect("lzma_default.7z should parse");
    assert_eq!(archive.file_count(), 1);

    let container = ContainerArchive::parse(&bytes).unwrap();
    let ms = container.header.main_streams.as_ref().unwrap();
    let folder = &ms.folders[0];
    assert_eq!(folder.coders[0].method_id, MethodId::lzma());
}

/// Parse a BZip2-compressed `.7z` archive.
#[test]
#[ignore = "bzip2_default.7z fixture not yet committed; un-ignore when BZip2 oracle fixture is generated"]
fn parses_bzip2_archive() {
    let bytes = fixture_bytes("bzip2_default.7z");
    let archive = Archive::parse(&bytes).expect("bzip2_default.7z should parse");
    assert_eq!(archive.file_count(), 1);

    let container = ContainerArchive::parse(&bytes).unwrap();
    let ms = container.header.main_streams.as_ref().unwrap();
    let folder = &ms.folders[0];
    assert_eq!(folder.coders[0].method_id, MethodId::bzip2());
}

/// Parse a Deflate-compressed `.7z` archive.
#[test]
#[ignore = "deflate_default.7z fixture not yet committed; un-ignore when Deflate oracle fixture is generated"]
fn parses_deflate_archive() {
    let bytes = fixture_bytes("deflate_default.7z");
    let archive = Archive::parse(&bytes).expect("deflate_default.7z should parse");
    assert_eq!(archive.file_count(), 1);
}
