//! Layer 5: cross-validation tests — 7zippy reads what 7zz writes; 7zz reads what 7zippy writes.
//!
//! Every test in this module requires the `7zz` CLI. Tests are skipped
//! automatically (via `require_7zz!()`) on machines where it is not installed.
//! CI is configured to always install `7zz`, so the skip never hides a real
//! failure in CI.
//!
//! Live tests cover the Copy coder. Every other codec row is `#[ignore]`d
//! until that codec is implemented.

use super::fixtures;
use super::oracle::require_7zz;
use super::oracle::{seven_zip_compress, seven_zip_decompress, CoderSpec};
use crate::{assert_slices_eq, Archive, ArchiveBuilder};

fn fixture_path(name: &str) -> std::path::PathBuf {
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest.join("corpora/fixtures/archives").join(name)
}

// ── 7zz reads what 7zippy writes ─────────────────────────────────────────────

/// Write a Copy-coder archive with 7zippy, then extract it with `7zz`.
///
/// Migrated and generalised from `oracle_copy::seven_zip_can_extract_our_copy_archive`.
#[test]
fn seven_zip_reads_our_copy_archive() {
    require_7zz!();

    let payload = b"Hello, from 7zippy's own writer!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_copy_file("greeting.txt", payload.clone());
    let archive_bytes = b.build().unwrap();

    // seven_zip_decompress writes the archive to a tempdir and runs 7zz x.
    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Write a 64 KiB Copy archive with 7zippy, extract with `7zz`.
#[test]
fn seven_zip_reads_our_copy_64k_archive() {
    require_7zz!();

    let input = fixtures::random(0x1234_5678, 65_536);
    let mut b = ArchiveBuilder::new();
    b.add_copy_file("payload.bin", input.clone());
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, input);
}

// ── 7zippy reads what 7zz writes ─────────────────────────────────────────────

/// Ask `7zz` to compress some bytes with the Copy coder, then read the
/// resulting archive with 7zippy.
#[test]
fn we_read_seven_zips_copy_archive() {
    require_7zz!();

    let input = fixtures::random(0xABCD_EF01, 1024);
    let archive = seven_zip_compress(&input, &CoderSpec::Copy);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz Copy archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

/// Read the committed `copy_only_64k.7z` fixture (generated by `7zz`) and
/// extract it with 7zippy.
#[test]
fn we_read_committed_copy_only_64k_fixture() {
    let bytes = std::fs::read(fixture_path("copy_only_64k.7z"))
        .expect("copy_only_64k.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse copy_only_64k.7z");
    assert_eq!(archive.file_count(), 1);
    assert_eq!(archive.file_name(0), Some("random_64k.bin"));
    let content = archive.reader().extract(0).unwrap();
    assert_eq!(content.len(), 65_536);
}

// ── LZMA cross-validation (live via lazippy wrapper) ─────────────────────────

/// Write a small LZMA archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "lzma")]
#[test]
fn seven_zip_reads_our_lzma_archive() {
    require_7zz!();

    use crate::pipeline::lzma::LzmaCoder;
    let payload = b"Hello, from 7zippy LZMA!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file("greeting.txt", payload.clone(), Box::new(LzmaCoder::new()));
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with LZMA, then decompress with 7zippy.
#[cfg(feature = "lzma")]
#[test]
fn we_read_seven_zips_lzma_archive() {
    require_7zz!();

    let input = fixtures::random(0xCAFEBABE, 1024);
    let archive = seven_zip_compress(
        &input,
        &CoderSpec::Lzma {
            level: 5,
            dict_size: None,
        },
    );

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz LZMA archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── BZip2 cross-validation (live via bzippy2 wrapper) ────────────────────────

/// Write a small BZip2 archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "bzip2")]
#[test]
fn seven_zip_reads_our_bzip2_archive() {
    require_7zz!();

    use crate::pipeline::bzip2::Bzip2Coder;
    let payload = b"Hello, from 7zippy BZip2!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file("greeting.txt", payload.clone(), Box::new(Bzip2Coder));
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with BZip2, then decompress with 7zippy.
#[cfg(feature = "bzip2")]
#[test]
fn we_read_seven_zips_bzip2_archive() {
    require_7zz!();

    let input = fixtures::random(0xB2B2_B2B2, 1024);
    let archive = seven_zip_compress(&input, &CoderSpec::Bzip2 { level: 5 });

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz BZip2 archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── LZMA2 cross-validation (live via lazippier sub-crate) ────────────────────

/// Write a small LZMA2 archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "lzma2")]
#[test]
fn seven_zip_reads_our_lzma2_archive() {
    require_7zz!();

    use crate::pipeline::lzma2::Lzma2Coder;
    let payload = b"Hello, from 7zippy LZMA2!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file("greeting.txt", payload.clone(), Box::new(Lzma2Coder::new()));
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with LZMA2, then decompress with 7zippy.
#[cfg(feature = "lzma2")]
#[test]
fn we_read_seven_zips_lzma2_archive() {
    require_7zz!();

    let input = fixtures::random(0xCAFE_BABE, 1024);
    let archive = seven_zip_compress(
        &input,
        &CoderSpec::Lzma2 {
            level: 5,
            dict_size: None,
        },
    );

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz LZMA2 archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

/// Read the committed LZMA2 fixture (generated by `7zz`) and extract it with 7zippy.
#[cfg(feature = "lzma2")]
#[test]
fn we_read_committed_lzma2_fixture() {
    let bytes = std::fs::read(fixture_path("lzma2_default.7z"))
        .expect("lzma2_default.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse lzma2_default.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive.reader().extract(0).unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}

// ── Deflate cross-validation (live via flate2 backend) ───────────────────────

/// Write a small Deflate archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "deflate")]
#[test]
fn seven_zip_reads_our_deflate_archive() {
    require_7zz!();

    use crate::pipeline::deflate::DeflateCoder;
    let payload = b"Hello, from 7zippy Deflate!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file("greeting.txt", payload.clone(), Box::new(DeflateCoder));
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with Deflate, then decompress with 7zippy.
#[cfg(feature = "deflate")]
#[test]
fn we_read_seven_zips_deflate_archive() {
    require_7zz!();

    let input = fixtures::random(0x0DEF_1A7E, 1024);
    let archive = seven_zip_compress(&input, &CoderSpec::Deflate { level: 5 });

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz Deflate archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── Delta cross-validation (in-tree pure-Rust implementation) ────────────────

/// Write a small Delta archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "delta")]
#[test]
fn seven_zip_reads_our_delta_archive() {
    require_7zz!();

    use crate::pipeline::delta::DeltaCoder;
    let payload = b"Hello, from 7zippy Delta!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file(
        "greeting.txt",
        payload.clone(),
        Box::new(DeltaCoder::new(1)),
    );
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with the Delta filter (standalone), then decompress
/// with 7zippy.
#[cfg(feature = "delta")]
#[test]
fn we_read_seven_zips_delta_archive() {
    require_7zz!();

    // Use a sequential byte pattern — highly predictable, so delta-encoding
    // collapses it to all-1s which is a good functional check.
    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::Delta { distance: 1 });

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz Delta archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

/// Read the committed delta fixture (generated by `7zz`) and extract it with 7zippy.
#[cfg(feature = "delta")]
#[test]
fn we_read_committed_delta_fixture() {
    let bytes = std::fs::read(fixture_path("delta_distance1.7z"))
        .expect("delta_distance1.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse delta_distance1.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive.reader().extract(0).unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}

// ── PPMd cross-validation (live via pippyzippy wrapper) ──────────────────────

/// Write a small PPMd archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "ppmd")]
#[test]
fn seven_zip_reads_our_ppmd_archive() {
    require_7zz!();

    use crate::pipeline::ppmd::PpmdCoder;
    let payload = b"Hello, from 7zippy PPMd!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file("greeting.txt", payload.clone(), Box::new(PpmdCoder::new()));
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with PPMd, then decompress with 7zippy.
#[cfg(feature = "ppmd")]
#[test]
fn we_read_seven_zips_ppmd_archive() {
    require_7zz!();

    let input = fixtures::ascii_paragraph(1024);
    let archive = seven_zip_compress(
        &input,
        &CoderSpec::Ppmd {
            level: 5,
            order: None,
        },
    );

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz PPMd archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── Deflate64 cross-validation (decode-only; in-tree via deflate64 crate) ────

/// Read the committed Deflate64 fixture (generated by `7zz`) and extract it with 7zippy.
///
/// This is a decode-only test — Deflate64 has no Rust encoder.
/// Fixture: bytes(range(256)) * 4 = 1024 bytes, encoded with `7zz -m0=deflate64`.
#[cfg(feature = "deflate64")]
#[test]
fn we_read_committed_deflate64_fixture() {
    let bytes = std::fs::read(fixture_path("deflate64_default.7z"))
        .expect("deflate64_default.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse deflate64_default.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive.reader().extract(0).unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}

/// Ask `7zz` to compress data with Deflate64, then decompress with 7zippy.
#[cfg(feature = "deflate64")]
#[test]
fn we_read_seven_zips_deflate64_archive() {
    require_7zz!();

    use super::oracle::CoderSpec;
    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::Deflate64);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz Deflate64 archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── BCJ cross-validation (live via lzma-rust2 filter module) ─────────────────

/// Write a small BCJ x86 archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "bcj")]
#[test]
fn seven_zip_reads_our_bcj_archive() {
    require_7zz!();

    use crate::pipeline::bcj::{BcjArch, BcjCoder};
    let payload = b"Hello, from 7zippy BCJ!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file(
        "greeting.txt",
        payload.clone(),
        Box::new(BcjCoder::new(BcjArch::X86)),
    );
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with the BCJ x86 filter (standalone), then
/// decompress with 7zippy.
#[cfg(feature = "bcj")]
#[test]
fn we_read_seven_zips_bcj_archive() {
    require_7zz!();

    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::Bcj);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz BCJ archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

/// Read the committed BCJ x86 fixture (generated by `7zz`) and extract it with 7zippy.
#[cfg(feature = "bcj")]
#[test]
fn we_read_committed_bcj_fixture() {
    let bytes = std::fs::read(fixture_path("bcj_x86.7z")).expect("bcj_x86.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse bcj_x86.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive.reader().extract(0).unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}

// ── BCJ2 cross-validation (decode-only; 4-stream via jumpzippier sub-crate) ──

/// Read the committed BCJ2+LZMA fixture (generated by `7zz`) and extract it with 7zippy.
///
/// BCJ2 is decode-only in Phase 1 — no encoder. The fixture contains
/// bytes(range(256)) * 4 = 1024 bytes encoded with `7zz -m0=BCJ2 -m1=LZMA`.
#[cfg(feature = "bcj2")]
#[test]
fn we_read_committed_bcj2_fixture() {
    let bytes =
        std::fs::read(fixture_path("bcj2_lzma.7z")).expect("bcj2_lzma.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse bcj2_lzma.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive.reader().extract(0).unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}

/// Ask `7zz` to compress data with BCJ2+LZMA, then decompress with 7zippy.
#[cfg(feature = "bcj2")]
#[test]
fn we_read_seven_zips_bcj2_archive() {
    require_7zz!();

    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::Bcj2);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz BCJ2 archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

/// Read the committed PPMd fixture (generated by `7zz`) and extract it with 7zippy.
#[cfg(feature = "ppmd")]
#[test]
fn we_read_committed_ppmd_fixture() {
    let bytes =
        std::fs::read(fixture_path("ppmd_default.7z")).expect("ppmd_default.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse ppmd_default.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive.reader().extract(0).unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}
