//! Layer 5: cross-validation tests — 7zippy reads what 7zz writes; 7zz reads what 7zippy writes.
//!
//! Every test in this module requires the `7zz` CLI. Tests are skipped
//! automatically (via `require_7zz!()`) on machines where it is not installed.
//! CI is configured to always install `7zz`, so the skip never hides a real
//! failure in CI.
//!
//! Live tests cover the Copy coder. Every other codec row is `#[ignore]`d
//! until that codec is implemented.

use super::fixtures;
use super::oracle::require_7zz;
use super::oracle::{seven_zip_compress, seven_zip_decompress, CoderSpec};
use crate::{assert_slices_eq, Archive, ArchiveBuilder};

fn fixture_path(name: &str) -> std::path::PathBuf {
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest.join("corpora/fixtures/archives").join(name)
}

// ── 7zz reads what 7zippy writes ─────────────────────────────────────────────

/// Write a Copy-coder archive with 7zippy, then extract it with `7zz`.
///
/// Migrated and generalised from `oracle_copy::seven_zip_can_extract_our_copy_archive`.
#[test]
fn seven_zip_reads_our_copy_archive() {
    require_7zz!();

    let payload = b"Hello, from 7zippy's own writer!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_copy_file("greeting.txt", payload.clone());
    let archive_bytes = b.build().unwrap();

    // seven_zip_decompress writes the archive to a tempdir and runs 7zz x.
    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Write a 64 KiB Copy archive with 7zippy, extract with `7zz`.
#[test]
fn seven_zip_reads_our_copy_64k_archive() {
    require_7zz!();

    let input = fixtures::random(0x1234_5678, 65_536);
    let mut b = ArchiveBuilder::new();
    b.add_copy_file("payload.bin", input.clone());
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, input);
}

// ── 7zippy reads what 7zz writes ─────────────────────────────────────────────

/// Ask `7zz` to compress some bytes with the Copy coder, then read the
/// resulting archive with 7zippy.
#[test]
fn we_read_seven_zips_copy_archive() {
    require_7zz!();

    let input = fixtures::random(0xABCD_EF01, 1024);
    let archive = seven_zip_compress(&input, &CoderSpec::Copy);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz Copy archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

/// Read the committed `copy_only_64k.7z` fixture (generated by `7zz`) and
/// extract it with 7zippy.
#[test]
fn we_read_committed_copy_only_64k_fixture() {
    let bytes = std::fs::read(fixture_path("copy_only_64k.7z"))
        .expect("copy_only_64k.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse copy_only_64k.7z");
    assert_eq!(archive.file_count(), 1);
    assert_eq!(archive.file_name(0), Some("random_64k.bin"));
    let content = archive.reader().extract(0).unwrap();
    assert_eq!(content.len(), 65_536);
}

// ── LZMA cross-validation (live via lazippy wrapper) ─────────────────────────

/// Write a small LZMA archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "lzma")]
#[test]
fn seven_zip_reads_our_lzma_archive() {
    require_7zz!();

    use crate::pipeline::lzma::LzmaCoder;
    let payload = b"Hello, from 7zippy LZMA!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file("greeting.txt", payload.clone(), Box::new(LzmaCoder::new()));
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with LZMA, then decompress with 7zippy.
#[cfg(feature = "lzma")]
#[test]
fn we_read_seven_zips_lzma_archive() {
    require_7zz!();

    let input = fixtures::random(0xCAFEBABE, 1024);
    let archive = seven_zip_compress(
        &input,
        &CoderSpec::Lzma {
            level: 5,
            dict_size: None,
        },
    );

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz LZMA archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── BZip2 cross-validation (live via bzippy2 wrapper) ────────────────────────

/// Write a small BZip2 archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "bzip2")]
#[test]
fn seven_zip_reads_our_bzip2_archive() {
    require_7zz!();

    use crate::pipeline::bzip2::Bzip2Coder;
    let payload = b"Hello, from 7zippy BZip2!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file("greeting.txt", payload.clone(), Box::new(Bzip2Coder));
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with BZip2, then decompress with 7zippy.
#[cfg(feature = "bzip2")]
#[test]
fn we_read_seven_zips_bzip2_archive() {
    require_7zz!();

    let input = fixtures::random(0xB2B2_B2B2, 1024);
    let archive = seven_zip_compress(&input, &CoderSpec::Bzip2 { level: 5 });

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz BZip2 archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── LZMA2 cross-validation (live via lazippier sub-crate) ────────────────────

/// Write a small LZMA2 archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "lzma2")]
#[test]
fn seven_zip_reads_our_lzma2_archive() {
    require_7zz!();

    use crate::pipeline::lzma2::Lzma2Coder;
    let payload = b"Hello, from 7zippy LZMA2!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file("greeting.txt", payload.clone(), Box::new(Lzma2Coder::new()));
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with LZMA2, then decompress with 7zippy.
#[cfg(feature = "lzma2")]
#[test]
fn we_read_seven_zips_lzma2_archive() {
    require_7zz!();

    let input = fixtures::random(0xCAFE_BABE, 1024);
    let archive = seven_zip_compress(
        &input,
        &CoderSpec::Lzma2 {
            level: 5,
            dict_size: None,
        },
    );

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz LZMA2 archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

/// Read the committed LZMA2 fixture (generated by `7zz`) and extract it with 7zippy.
#[cfg(feature = "lzma2")]
#[test]
fn we_read_committed_lzma2_fixture() {
    let bytes = std::fs::read(fixture_path("lzma2_default.7z"))
        .expect("lzma2_default.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse lzma2_default.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive.reader().extract(0).unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}

// ── Deflate cross-validation (live via flate2 backend) ───────────────────────

/// Write a small Deflate archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "deflate")]
#[test]
fn seven_zip_reads_our_deflate_archive() {
    require_7zz!();

    use crate::pipeline::deflate::DeflateCoder;
    let payload = b"Hello, from 7zippy Deflate!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file("greeting.txt", payload.clone(), Box::new(DeflateCoder));
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with Deflate, then decompress with 7zippy.
#[cfg(feature = "deflate")]
#[test]
fn we_read_seven_zips_deflate_archive() {
    require_7zz!();

    let input = fixtures::random(0x0DEF_1A7E, 1024);
    let archive = seven_zip_compress(&input, &CoderSpec::Deflate { level: 5 });

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz Deflate archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── Delta cross-validation (in-tree pure-Rust implementation) ────────────────

/// Write a small Delta archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "delta")]
#[test]
fn seven_zip_reads_our_delta_archive() {
    require_7zz!();

    use crate::pipeline::delta::DeltaCoder;
    let payload = b"Hello, from 7zippy Delta!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file(
        "greeting.txt",
        payload.clone(),
        Box::new(DeltaCoder::new(1)),
    );
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with the Delta filter (standalone), then decompress
/// with 7zippy.
#[cfg(feature = "delta")]
#[test]
fn we_read_seven_zips_delta_archive() {
    require_7zz!();

    // Use a sequential byte pattern — highly predictable, so delta-encoding
    // collapses it to all-1s which is a good functional check.
    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::Delta { distance: 1 });

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz Delta archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

/// Read the committed delta fixture (generated by `7zz`) and extract it with 7zippy.
#[cfg(feature = "delta")]
#[test]
fn we_read_committed_delta_fixture() {
    let bytes = std::fs::read(fixture_path("delta_distance1.7z"))
        .expect("delta_distance1.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse delta_distance1.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive.reader().extract(0).unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}

// ── PPMd cross-validation (live via pippyzippy wrapper) ──────────────────────

/// Write a small PPMd archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "ppmd")]
#[test]
fn seven_zip_reads_our_ppmd_archive() {
    require_7zz!();

    use crate::pipeline::ppmd::PpmdCoder;
    let payload = b"Hello, from 7zippy PPMd!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file("greeting.txt", payload.clone(), Box::new(PpmdCoder::new()));
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with PPMd, then decompress with 7zippy.
#[cfg(feature = "ppmd")]
#[test]
fn we_read_seven_zips_ppmd_archive() {
    require_7zz!();

    let input = fixtures::ascii_paragraph(1024);
    let archive = seven_zip_compress(
        &input,
        &CoderSpec::Ppmd {
            level: 5,
            order: None,
        },
    );

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz PPMd archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── Deflate64 cross-validation (encode + decode via gzippy 0.8) ──────────────

/// Encode bytes with 7zippy's Deflate64Coder, decode them back, assert equality.
///
/// This is a pure round-trip within 7zippy (no `7zz` required). Uses a varied
/// fixture: zeros, sequential bytes, and ASCII mixed together.
#[cfg(feature = "deflate64")]
#[test]
fn deflate64_round_trip() {
    use crate::pipeline::deflate64::Deflate64Coder;
    use crate::pipeline::Coder;

    // Varied fixture: zeros, sequential, ASCII.
    let mut payload: Vec<u8> = Vec::with_capacity(768);
    payload.extend(std::iter::repeat_n(0u8, 256));
    payload.extend(0u8..=255u8);
    payload.extend(
        b"Hello, from 7zippy Deflate64 round-trip test!"
            .iter()
            .cycle()
            .take(256),
    );

    let coder = Deflate64Coder;
    let compressed = coder.encode(&payload).expect("Deflate64 encode failed");
    let decompressed = coder
        .decode(&compressed, payload.len() as u64)
        .expect("Deflate64 decode failed");

    assert_eq!(
        decompressed, payload,
        "Deflate64 round-trip mismatch: encode then decode did not reproduce the original"
    );
}

/// Write a small Deflate64 archive with 7zippy, then extract it with `7zz`.
///
/// This is the oracle encode test: 7zippy produces the archive, 7zz verifies it.
#[cfg(feature = "deflate64")]
#[test]
fn seven_zip_reads_our_deflate64_archive() {
    require_7zz!();

    use crate::pipeline::deflate64::Deflate64Coder;
    let payload = b"Hello, from 7zippy Deflate64!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file("greeting.txt", payload.clone(), Box::new(Deflate64Coder));
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Read the committed Deflate64 fixture (generated by `7zz`) and extract it
/// with 7zippy (decode path).
///
/// Fixture: bytes(range(256)) * 4 = 1024 bytes, encoded with `7zz -m0=deflate64`.
#[cfg(feature = "deflate64")]
#[test]
fn we_read_committed_deflate64_fixture() {
    let bytes = std::fs::read(fixture_path("deflate64_default.7z"))
        .expect("deflate64_default.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse deflate64_default.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive.reader().extract(0).unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}

/// Ask `7zz` to compress data with Deflate64, then decompress with 7zippy
/// (oracle decode test — 7zz produces, 7zippy reads).
#[cfg(feature = "deflate64")]
#[test]
fn we_read_seven_zips_deflate64_archive() {
    require_7zz!();

    use super::oracle::CoderSpec;
    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::Deflate64);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz Deflate64 archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── BCJ cross-validation (live via lzma-rust2 filter module) ─────────────────

/// Write a small BCJ x86 archive with 7zippy, then extract it with `7zz`.
#[cfg(feature = "bcj")]
#[test]
fn seven_zip_reads_our_bcj_archive() {
    require_7zz!();

    use crate::pipeline::bcj::{BcjArch, BcjCoder};
    let payload = b"Hello, from 7zippy BCJ!".to_vec();
    let mut b = ArchiveBuilder::new();
    b.add_file(
        "greeting.txt",
        payload.clone(),
        Box::new(BcjCoder::new(BcjArch::X86)),
    );
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Ask `7zz` to compress data with the BCJ x86 filter (standalone), then
/// decompress with 7zippy.
#[cfg(feature = "bcj")]
#[test]
fn we_read_seven_zips_bcj_archive() {
    require_7zz!();

    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::Bcj);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz BCJ archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

/// Read the committed BCJ x86 fixture (generated by `7zz`) and extract it with 7zippy.
#[cfg(feature = "bcj")]
#[test]
fn we_read_committed_bcj_fixture() {
    let bytes = std::fs::read(fixture_path("bcj_x86.7z")).expect("bcj_x86.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse bcj_x86.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive.reader().extract(0).unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}

// ── BCJ ARM oracle tests ───────────────────────────────────────────────────────

/// Write a BCJ ARM archive with 7zippy, then extract it with `7zz`.
///
/// Fixture: 1024 bytes of cycling 0–255, which contains ARM branch-like byte
/// patterns (0xEB / 0xEA at word-aligned offsets) that the ARM BCJ filter
/// transforms.
#[cfg(feature = "bcj")]
#[test]
fn seven_zip_reads_our_bcj_arm_archive() {
    require_7zz!();

    use crate::pipeline::bcj::{BcjArch, BcjCoder};
    use crate::pipeline::Coder;
    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let coder = BcjCoder::new(BcjArch::Arm);
    let filtered = coder.encode(&input).unwrap();
    assert_ne!(
        filtered, input,
        "BCJ ARM filter must transform the fixture (sanity: filter is not a no-op)"
    );

    let mut b = ArchiveBuilder::new();
    b.add_file(
        "payload.bin",
        input.clone(),
        Box::new(BcjCoder::new(BcjArch::Arm)),
    );
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, input);
}

/// Ask `7zz` to compress data with the BCJ ARM filter, then decompress with 7zippy.
#[cfg(feature = "bcj")]
#[test]
fn bcj_arm_oracle_round_trip() {
    require_7zz!();

    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::BcjArm);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz BCJ ARM archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── BCJ ARM-Thumb oracle tests ─────────────────────────────────────────────────

/// Write a BCJ ARM-Thumb archive with 7zippy, then extract it with `7zz`.
///
/// Fixture: 1024 bytes of cycling 0–255, which contains Thumb2 BL-like byte
/// patterns that the ARM-Thumb BCJ filter transforms.
#[cfg(feature = "bcj")]
#[test]
fn seven_zip_reads_our_bcj_arm_thumb_archive() {
    require_7zz!();

    use crate::pipeline::bcj::{BcjArch, BcjCoder};
    use crate::pipeline::Coder;
    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let coder = BcjCoder::new(BcjArch::ArmThumb);
    let filtered = coder.encode(&input).unwrap();
    assert_ne!(
        filtered, input,
        "BCJ ARM-Thumb filter must transform the fixture (sanity: filter is not a no-op)"
    );

    let mut b = ArchiveBuilder::new();
    b.add_file(
        "payload.bin",
        input.clone(),
        Box::new(BcjCoder::new(BcjArch::ArmThumb)),
    );
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, input);
}

/// Ask `7zz` to compress data with the BCJ ARM-Thumb filter, then decompress with 7zippy.
#[cfg(feature = "bcj")]
#[test]
fn bcj_arm_thumb_oracle_round_trip() {
    require_7zz!();

    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::BcjArmThumb);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz BCJ ARM-Thumb archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── BCJ PPC oracle tests ───────────────────────────────────────────────────────

/// Write a BCJ PPC archive with 7zippy, then extract it with `7zz`.
///
/// Fixture: repeated `[0x48, 0x00, 0x04, 0x01]` — a PPC BL (branch-and-link,
/// AA=0) instruction pointing to a relative offset. The PPC BCJ filter triggers
/// on 4-byte words where `(b0 & 0xFC) == 0x48 && (b3 & 0x03) == 0x01`. At
/// pos > 0 the filter adds the program counter, so output differs from input.
#[cfg(feature = "bcj")]
#[test]
fn seven_zip_reads_our_bcj_ppc_archive() {
    require_7zz!();

    use crate::pipeline::bcj::{BcjArch, BcjCoder};
    use crate::pipeline::Coder;
    // PPC BL (branch-and-link, AA=0): opcode=18, LK=1, AA=0 → last byte 0x01.
    // At pos=4 the filter adds 4 to the src offset, changing the output bytes.
    let input: Vec<u8> = [0x48u8, 0x00, 0x04, 0x01].repeat(256); // 1024 bytes
    let coder = BcjCoder::new(BcjArch::PowerPc);
    let filtered = coder.encode(&input).unwrap();
    assert_ne!(
        filtered, input,
        "BCJ PPC filter must transform the fixture (sanity: filter is not a no-op)"
    );

    let mut b = ArchiveBuilder::new();
    b.add_file(
        "payload.bin",
        input.clone(),
        Box::new(BcjCoder::new(BcjArch::PowerPc)),
    );
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, input);
}

/// Ask `7zz` to compress data with the BCJ PPC filter, then decompress with 7zippy.
#[cfg(feature = "bcj")]
#[test]
fn bcj_ppc_oracle_round_trip() {
    require_7zz!();

    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::BcjPpc);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz BCJ PPC archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── BCJ IA64 oracle tests ──────────────────────────────────────────────────────

/// Write a BCJ IA64 archive with 7zippy, then extract it with `7zz`.
///
/// Fixture: hand-crafted 16-byte IA64 bundle with template 0x10 (MFB — M, F,
/// and B-type slots). The last slot is a branch (`op=5`, `btype=0`) with a
/// non-zero relative target. At bundle-position > 0 the filter adds the PC,
/// so output bytes differ from input.
#[cfg(feature = "bcj")]
#[test]
fn seven_zip_reads_our_bcj_ia64_archive() {
    require_7zz!();

    use crate::pipeline::bcj::{BcjArch, BcjCoder};
    use crate::pipeline::Coder;
    // Bundle: template=0x10 (MFB). Slot 2 (branch) at bit_pos=87, byte_pos=10,
    // bit_res=7. instr_norm = (5<<37)|(1<<13) = 0xA000002000 encodes a branch
    // with 20-bit offset=1 and op=5 btype=0. The 6 bytes at [10..16] in LE are:
    //   instr = instr_norm << 7 = 0x500000100000
    //   bytes: 0x00, 0x00, 0x10, 0x00, 0x00, 0x50
    // At pos > 0 the PC is added to the src offset, modifying the output.
    let bundle: [u8; 16] = [
        0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00,
        0x50,
    ];
    let input: Vec<u8> = bundle.repeat(64); // 1024 bytes = 64 bundles
    let coder = BcjCoder::new(BcjArch::Ia64);
    let filtered = coder.encode(&input).unwrap();
    assert_ne!(
        filtered, input,
        "BCJ IA64 filter must transform the fixture (sanity: filter is not a no-op)"
    );

    let mut b = ArchiveBuilder::new();
    b.add_file(
        "payload.bin",
        input.clone(),
        Box::new(BcjCoder::new(BcjArch::Ia64)),
    );
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, input);
}

/// Ask `7zz` to compress data with the BCJ IA64 filter, then decompress with 7zippy.
#[cfg(feature = "bcj")]
#[test]
fn bcj_ia64_oracle_round_trip() {
    require_7zz!();

    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::BcjIa64);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz BCJ IA64 archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── BCJ SPARC oracle tests ─────────────────────────────────────────────────────

/// Write a BCJ SPARC archive with 7zippy, then extract it with `7zz`.
///
/// Fixture: repeated `[0x40, 0x00, 0x04, 0x00]` — a SPARC CALL instruction
/// with a small non-zero displacement. The SPARC BCJ filter triggers on 4-byte
/// words where `b0 == 0x40 && (b1 & 0xC0) == 0x00`. At pos > 0 the filter
/// adds the program counter to the disp30 field, changing the output bytes.
#[cfg(feature = "bcj")]
#[test]
fn seven_zip_reads_our_bcj_sparc_archive() {
    require_7zz!();

    use crate::pipeline::bcj::{BcjArch, BcjCoder};
    use crate::pipeline::Coder;
    // SPARC CALL: op=01 (bits 31-30), disp30 = 0x000400 (non-zero displacement).
    // [0x40, 0x00, 0x04, 0x00] satisfies b0==0x40 and (b1&0xC0)==0x00.
    // At pos=4 the filter adds 4 to the shifted src, changing the output.
    let input: Vec<u8> = [0x40u8, 0x00, 0x04, 0x00].repeat(256); // 1024 bytes
    let coder = BcjCoder::new(BcjArch::Sparc);
    let filtered = coder.encode(&input).unwrap();
    assert_ne!(
        filtered, input,
        "BCJ SPARC filter must transform the fixture (sanity: filter is not a no-op)"
    );

    let mut b = ArchiveBuilder::new();
    b.add_file(
        "payload.bin",
        input.clone(),
        Box::new(BcjCoder::new(BcjArch::Sparc)),
    );
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, input);
}

/// Ask `7zz` to compress data with the BCJ SPARC filter, then decompress with 7zippy.
#[cfg(feature = "bcj")]
#[test]
fn bcj_sparc_oracle_round_trip() {
    require_7zz!();

    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::BcjSparc);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz BCJ SPARC archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── BCJ2 cross-validation (decode-only; 4-stream via jumpzippier sub-crate) ──

/// Read the committed BCJ2+LZMA fixture (generated by `7zz`) and extract it with 7zippy.
///
/// BCJ2 is decode-only in Phase 1 — no encoder. The fixture contains
/// bytes(range(256)) * 4 = 1024 bytes encoded with `7zz -m0=BCJ2 -m1=LZMA`.
#[cfg(feature = "bcj2")]
#[test]
fn we_read_committed_bcj2_fixture() {
    let bytes =
        std::fs::read(fixture_path("bcj2_lzma.7z")).expect("bcj2_lzma.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse bcj2_lzma.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive.reader().extract(0).unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}

/// Ask `7zz` to compress data with BCJ2+LZMA, then decompress with 7zippy.
#[cfg(feature = "bcj2")]
#[test]
fn we_read_seven_zips_bcj2_archive() {
    require_7zz!();

    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(&input, &CoderSpec::Bcj2);

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz BCJ2 archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed.reader().extract(0).unwrap();
    assert_slices_eq!(extracted, input);
}

// ── AES cross-validation (decode-only; via lockzippy sub-crate) ──────────────

/// Read the committed AES+LZMA2 fixture (generated by `7zz`) and extract it with 7zippy.
///
/// This is a decrypt + decompress test — AES encryption has no pure-Rust encoder
/// in Phase 1. The fixture contains bytes(range(256)) * 4 = 1024 bytes encrypted
/// with `7zz -p"test1234"` (default LZMA2 compression + AES-256 encryption).
///
/// Password: "test1234"
#[cfg(feature = "aes")]
#[test]
fn we_read_committed_aes_fixture() {
    let bytes =
        std::fs::read(fixture_path("aes_lzma2.7z")).expect("aes_lzma2.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse aes_lzma2.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive
        .reader()
        .extract_with_password(0, "test1234")
        .unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}

/// Ask `7zz` to encrypt data with AES+LZMA2, then decrypt + decompress with 7zippy.
#[cfg(feature = "aes")]
#[test]
fn we_read_seven_zips_aes_archive() {
    require_7zz!();

    let input: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    let archive = seven_zip_compress(
        &input,
        &CoderSpec::Aes {
            password: "test1234".to_string(),
        },
    );

    let parsed = Archive::parse(&archive).expect("7zippy must parse 7zz AES archive");
    assert_eq!(parsed.file_count(), 1);
    let extracted = parsed
        .reader()
        .extract_with_password(0, "test1234")
        .unwrap();
    assert_slices_eq!(extracted, input);
}

/// Write an AES+LZMA2 archive with 7zippy (using `add_encrypted_file`), then
/// extract it with `7zz`. This is the deferred oracle test from PR #7.
///
/// Password: "test1234". Payload: 64 KiB of seeded pseudo-random bytes.
#[cfg(all(feature = "aes", feature = "lzma2"))]
#[test]
fn seven_zip_extracts_our_aes_lzma2_archive() {
    require_7zz!();

    let input = fixtures::random(0xAE5_AE5_AE5_AE5u64, 65_536);

    let mut b = ArchiveBuilder::new();
    b.add_encrypted_file("payload.bin", input.clone(), "test1234");
    let archive_bytes = b.build().unwrap();

    // seven_zip_decompress writes the archive and runs `7zz x -p<password>`.
    // We need password support — call 7zz directly since seven_zip_decompress
    // doesn't accept a password argument.
    use super::oracle::seven_zz_path;
    use std::process::{Command, Stdio};

    let sevenzip = seven_zz_path().expect("7zz must be installed");
    let tmp = tempfile::tempdir().expect("tempdir failed");
    let archive_path = tmp.path().join("archive.7z");
    let out_dir = tmp.path().join("out");
    std::fs::create_dir_all(&out_dir).expect("create out dir failed");
    std::fs::write(&archive_path, &archive_bytes).expect("write archive failed");

    let output = Command::new(&sevenzip)
        .arg("x")
        .arg(format!("-o{}", out_dir.display()))
        .arg("-ptest1234")
        .arg("-y")
        .arg(&archive_path)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .expect("failed to spawn 7zz");

    assert!(
        output.status.success(),
        "7zz x failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    // Find and read the extracted file.
    let extracted_path = out_dir.join("payload.bin");
    let extracted = std::fs::read(&extracted_path)
        .unwrap_or_else(|e| panic!("failed to read extracted payload.bin: {e}"));

    assert_slices_eq!(extracted, input);
}

/// Write an AES+LZMA2 archive with 7zippy and round-trip it through 7zippy's
/// own reader (no `7zz` required).
#[cfg(all(feature = "aes", feature = "lzma2"))]
#[test]
fn seven_zippy_round_trips_aes_lzma2_archive() {
    let input = fixtures::random(0xAE5_CAFE_BEEF_u64, 8_192);
    let password = "roundtrip42";

    let mut b = ArchiveBuilder::new();
    b.add_encrypted_file("data.bin", input.clone(), password);
    let archive_bytes = b.build().expect("build failed");

    let archive = Archive::parse(&archive_bytes).expect("parse failed");
    assert_eq!(archive.file_count(), 1);
    assert_eq!(archive.file_name(0), Some("data.bin"));

    let extracted = archive
        .reader()
        .extract_with_password(0, password)
        .expect("extract_with_password failed");

    assert_slices_eq!(extracted, input);
}

/// Attempting to extract an encrypted archive without a password returns an error.
#[cfg(feature = "aes")]
#[test]
fn extract_without_password_returns_encrypted_error() {
    let bytes =
        std::fs::read(fixture_path("aes_lzma2.7z")).expect("aes_lzma2.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse aes_lzma2.7z");
    let result = archive.reader().extract(0);
    assert!(
        matches!(result, Err(crate::SevenZippyError::EncryptedContent(_))),
        "expected EncryptedContent error, got: {result:?}"
    );
}

/// Read the committed PPMd fixture (generated by `7zz`) and extract it with 7zippy.
#[cfg(feature = "ppmd")]
#[test]
fn we_read_committed_ppmd_fixture() {
    let bytes =
        std::fs::read(fixture_path("ppmd_default.7z")).expect("ppmd_default.7z must be committed");
    let archive = Archive::parse(&bytes).expect("must parse ppmd_default.7z");
    assert_eq!(archive.file_count(), 1);
    let content = archive.reader().extract(0).unwrap();
    // Payload is bytes(range(256)) * 4 = 1024 bytes
    let expected: Vec<u8> = (0u8..=255).cycle().take(1024).collect();
    assert_slices_eq!(content, expected);
}

// ── BCJ2 encode oracle (Phase 1 closure) ─────────────────────────────────────

/// Write a BCJ2+LZMA archive with 7zippy, then extract it with `7zz`.
///
/// This is the headline Phase 1 closure test. It uses a cycling 0..=255
/// fixture that statistically contains `E8` (CALL), `E9` (JMP), and `0F 8x`
/// (Jcc) opcodes, exercising all three BCJ2 branch streams.
///
/// The archive is built with `ArchiveBuilder::add_bcj2_file`, which routes
/// through `encode_bcj2_folder` → `jumpzippier::encode::encode_4streams` +
/// LZMA. The resulting 4-packed-stream folder must be parseable by `7zz`.
#[cfg(feature = "bcj2")]
#[test]
fn seven_zip_reads_our_bcj2_archive() {
    require_7zz!();

    // Use a cycling 0..=255 fixture (4 KiB). This fixture contains:
    //   - 0xE8 bytes (CALL opcode candidates)
    //   - 0xE9 bytes (JMP opcode candidates)
    //   - 0x0F bytes followed by 0x80-0x8F (Jcc candidates)
    // providing good coverage of all 4 BCJ2 branch streams.
    let payload: Vec<u8> = (0u8..=255).cycle().take(4096).collect();

    let mut b = ArchiveBuilder::new();
    b.add_bcj2_file("test.bin", payload.clone());
    let archive_bytes = b.build().unwrap();

    // seven_zip_decompress writes the archive to a tempdir and runs `7zz x`.
    // STOP-AND-REPORT: if 7zz rejects the archive (panics here), the
    // multi-pack-stream container fields are wrong.
    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}

/// Reverse direction: ask `7zz` to compress data with BCJ2+LZMA, then read
/// the resulting archive with 7zippy.
///
/// This test already exists as `we_read_seven_zips_bcj2_archive` (decode-only
/// path), but we re-assert it here to confirm nothing regressed.
#[cfg(feature = "bcj2")]
#[test]
fn seven_zip_reads_our_bcj2_archive_larger_payload() {
    require_7zz!();

    // 16 KiB cycling fixture — more E8/E9/0F patterns than the 4 KiB version.
    let payload: Vec<u8> = (0u8..=255).cycle().take(16384).collect();

    let mut b = ArchiveBuilder::new();
    b.add_bcj2_file("large.bin", payload.clone());
    let archive_bytes = b.build().unwrap();

    let extracted = seven_zip_decompress(&archive_bytes);
    assert_slices_eq!(extracted, payload);
}
